---
# tasks file for include_import
- name: test ping
  ping:

- name: Create folder1
  file
    path: ~/impinc/folder1
    state: directory
    mode: 0755

- name: Create folder2
  file
    path: ~/impinc/folder2
    state: directory
    mode: 0755

- name: Create file1
  copy: 
    dest: ~/impinc/file1.txt
    content: |
      Text Line1, in file1
      Text Line2, in file1
      Text Line3, {{ mytext }}

- name: Create file2
  copy:
    dest: ~/impinc/file2.txt
    content: |
      Text Line1, in file2
      Text Line2, in file2
      Text Line3, {{ mytext }}



